<?php
require_once($_SERVER['DOCUMENT_ROOT'].'/templates/_functions.php');

//Change page name here:
$PageName = 'Marand';

require_once($_SERVER['DOCUMENT_ROOT'].'/templates/_header.php');
?>

		<div id="Content">
<!-- - - - - - - - - - - - - - - - - - - - - - - Content starts here - - - - - - - - - - - - - - - - - - - - - - - - - -->
		
			<h1><?php echo "$PageName";?></h1>
			
			<a href="http://www.marand.com/" target="_blank"><img src="/files/industry_partners/marand_logo.png" class="IndustryLogoImg"></a>
			
			<p><em>Headquarters:</em> Slovenia</p>
			<p><em>Size:</em> 110 employees</p>
			<p><em>Trading since:</em> 1989</p>
			<p><a href="http://www.marand.com/" target="_blank">website</a></p>
			<br/>
			<br/>
			
			<h2>Solutions</h2>
			<p><a href ="http://www.marand-think.com/" target="_blank">Think!EHR Platform&#8482;</a> is a health data repository based on open standards. It provides a solid foundation to jumpstart development of state-of-the-art healthcare apps and applications.</p>
			<p><a href="http://www.marand-thinkmed.com/" target="_blank">Think!Med Clinical&#8482;</a> is a Hospital information System based on Think!EHR PlatformTM and includes a longitudinal electronic record of patient health information generated by encounters in any care delivery setting.</p>
			
			<h2>Customers</h2>
			<p>University Medical Center Ljubljana, Slovenia: Think!Med Clinical&#8482; has been running in production at the 220 bed Children's Hospital for two years, spreading now to other hospitals (Infections Clinic, Cardio Surgery).</p>
			<p>Ministry of Health, Slovenia: National health information exchange network enabling sharing of clinical information among all healthcare stakeholders. Think!EHR Platform&#8482; is part of the interoperability backbone providing a clinical data repository to eHealth applications.</p>
			<p>Institute of Oncology, Slovenia: Think!EHR Platform&#8482; provides a clinical data repository for Slovenia's National Breast Cancer Screening program.</p>
			<p>City of Moscow, Russia: Think!EHR platform&#8482; as health data platform for centralized electronic health records for Moscow's inhabitants.</p>
		
<!-- - - - - - - - - - - - - - - - - - - - - - - Content ends here - - - - - - - - - - - - - - - - - - - - - - - - - -->
		</div>	
<?php require_once($_SERVER['DOCUMENT_ROOT'].'/templates/_footer.php');?>
